import type { Campaign, Character, Location, Session } from "./types";

export const mockCampaigns: Campaign[] = [
  {
    id: "1",
    name: "The Lost Mines of Phandelver",
    description:
      "A classic adventure for new heroes seeking fame and fortune in the dangerous ruins of an ancient dwarven mine.",
    setting: "Forgotten Realms",
    theme: "Fantasy Adventure",
    difficulty: "Beginner",
    isActive: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
    sessions: [
      {
        id: "s1",
        campaignId: "1",
        title: "Session 1: Goblin Ambush",
        name: "Session 1: Goblin Ambush",
        description:
          "The adventure begins with an ambush on the road to Phandelver",
        date: new Date("2024-01-20"),
        isCompleted: true,
        sessionNumber: 1,
        isActive: false,
        status: "Completed",
        duration: 120,
        createdAt: new Date("2024-01-20"),
        updatedAt: new Date("2024-01-20"),
      },
      {
        id: "s2",
        campaignId: "1",
        title: "Session 2: Cragmaw Hideout",
        name: "Session 2: Cragmaw Hideout",
        description: "Exploring the goblin hideout and rescuing Sildar",
        date: new Date("2024-01-27"),
        isCompleted: true,
        sessionNumber: 2,
        isActive: false,
        status: "Completed",
        duration: 150,
        createdAt: new Date("2024-01-27"),
        updatedAt: new Date("2024-01-27"),
      },
      {
        id: "s4",
        campaignId: "1",
        title: "Session 4: Phandelver",
        name: "Session 4: Phandelver",
        description: "Arriving in Phandelver and meeting the locals",
        date: new Date("2024-02-10"),
        isCompleted: false,
        sessionNumber: 4,
        isActive: true,
        status: "In Progress",
        duration: 90,
        createdAt: new Date("2024-02-10"),
        updatedAt: new Date("2024-02-10"),
      },
    ],
  },
  {
    id: "2",
    name: "Curse of Strahd",
    description:
      "A gothic horror adventure in the mist-shrouded realm of Barovia, ruled by the vampire lord Strahd von Zarovich.",
    setting: "Ravenloft",
    theme: "Gothic Horror",
    difficulty: "Advanced",
    isActive: true,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
    sessions: [
      {
        id: "s3",
        campaignId: "2",
        title: "Session 1: Into the Mists",
        name: "Session 1: Into the Mists",
        description:
          "The party finds themselves trapped in the mysterious realm of Barovia",
        date: new Date("2024-02-03"),
        isCompleted: false,
        sessionNumber: 1,
        isActive: true,
        status: "In Progress",
        duration: 180,
        createdAt: new Date("2024-02-03"),
        updatedAt: new Date("2024-02-03"),
      },
    ],
  },
  {
    id: "3",
    name: "Dragon Heist",
    description:
      "Urban intrigue and treasure hunting in the great city of Waterdeep.",
    setting: "Waterdeep",
    theme: "Urban Intrigue",
    difficulty: "Intermediate",
    isActive: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-10"),
    sessions: [],
  },
];

export const mockCharacters: Character[] = [
  {
    id: "1",
    campaignId: "1",
    name: "Thorin Ironforge",
    race: "Dwarf",
    class: "Fighter",
    level: 3,
    alignment: "Lawful Good",
    background: "Soldier",
    hitPoints: {
      current: 28,
      maximum: 32,
    },
    armorClass: 18,
    proficiencyBonus: 2,
    stats: {
      strength: 16,
      dexterity: 12,
      constitution: 15,
      intelligence: 10,
      wisdom: 13,
      charisma: 8,
    },
    skills: ["Athletics", "Intimidation", "Perception", "Survival"],
    equipment: [
      "Warhammer",
      "Chain Mail",
      "Shield",
      "Handaxe",
      "Explorer's Pack",
    ],
    backstory:
      "A veteran soldier who has seen many battles and seeks to protect the innocent.",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    campaignId: "1",
    name: "Elara Moonwhisper",
    race: "Elf",
    class: "Wizard",
    level: 2,
    alignment: "Neutral Good",
    background: "Sage",
    hitPoints: {
      current: 12,
      maximum: 14,
    },
    armorClass: 12,
    proficiencyBonus: 2,
    stats: {
      strength: 8,
      dexterity: 14,
      constitution: 13,
      intelligence: 16,
      wisdom: 12,
      charisma: 11,
    },
    skills: ["Arcana", "History", "Investigation", "Medicine"],
    equipment: [
      "Quarterstaff",
      "Dagger",
      "Spellbook",
      "Scholar's Pack",
      "Component Pouch",
    ],
    spells: ["Magic Missile", "Shield", "Detect Magic", "Identify", "Sleep"],
    backstory:
      "A scholarly elf who seeks ancient knowledge and magical secrets.",
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "3",
    campaignId: "2",
    name: "Finn Lightfinger",
    race: "Halfling",
    class: "Rogue",
    level: 2,
    alignment: "Chaotic Good",
    background: "Criminal",
    hitPoints: {
      current: 16,
      maximum: 16,
    },
    armorClass: 15,
    proficiencyBonus: 2,
    stats: {
      strength: 10,
      dexterity: 16,
      constitution: 14,
      intelligence: 12,
      wisdom: 10,
      charisma: 14,
    },
    skills: ["Acrobatics", "Deception", "Sleight of Hand", "Stealth"],
    equipment: [
      "Shortsword",
      "Shortbow",
      "Leather Armor",
      "Thieves' Tools",
      "Burglar's Pack",
    ],
    backstory: "A reformed thief who now uses his skills for good causes.",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
];

export const mockLocations: Location[] = [
  {
    id: "1",
    campaignId: "1",
    name: "Phandelver",
    type: "city",
    description:
      "A small mining town nestled in the foothills of the Sword Mountains.",
    difficulty: "Safe",
    inhabitants: ["Miner families", "Merchants", "Town guards"],
    connections: ["Neverwinter", "Triboar", "Cragmaw Hideout"],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "2",
    campaignId: "1",
    name: "Cragmaw Hideout",
    type: "dungeon",
    description:
      "A cave system serving as a goblin hideout, carved into a hillside.",
    difficulty: "Easy",
    inhabitants: ["Goblins", "Wolves"],
    connections: ["Phandelver", "Cragmaw Castle"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "3",
    campaignId: "2",
    name: "Village of Barovia",
    type: "city",
    description:
      "A gloomy village surrounded by mist, with dark secrets lurking in every shadow.",
    difficulty: "Dangerous",
    inhabitants: ["Villagers", "Vistani", "Undead"],
    connections: ["Castle Ravenloft", "Tser Pool", "Old Bonegrinder"],
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
];
