import type { Campaign, Character, Location, Session } from "./types"

export const mockCampaigns: Campaign[] = [
  {
    id: "1",
    name: "The Lost Mines of Phandelver",
    description:
      "A classic adventure for new heroes seeking fame and fortune in the dangerous ruins of an ancient dwarven mine.",
    setting: "Forgotten Realms",
    isActive: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
    sessions: [],
  },
  {
    id: "2",
    name: "Curse of Strahd",
    description:
      "A gothic horror adventure in the mist-shrouded realm of Barovia, ruled by the vampire lord Strahd von Zarovich.",
    setting: "Ravenloft",
    isActive: true,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
    sessions: [],
  },
  {
    id: "3",
    name: "Dragon Heist",
    description: "Urban intrigue and treasure hunting in the great city of Waterdeep.",
    setting: "Waterdeep",
    isActive: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-10"),
    sessions: [],
  },
]

export const mockCharacters: Character[] = [
  {
    id: "1",
    campaignId: "1",
    name: "Thorin Ironforge",
    race: "Dwarf",
    class: "Fighter",
    level: 3,
    alignment: "Lawful Good",
    background: "Soldier",
    hitPoints: {
      current: 28,
      maximum: 32,
    },
    armorClass: 18,
    proficiencyBonus: 2,
    stats: {
      strength: 16,
      dexterity: 12,
      constitution: 15,
      intelligence: 10,
      wisdom: 13,
      charisma: 8,
    },
    skills: ["Athletics", "Intimidation", "Perception", "Survival"],
    equipment: ["Warhammer", "Chain Mail", "Shield", "Handaxe", "Explorer's Pack"],
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    campaignId: "1",
    name: "Elara Moonwhisper",
    race: "Elf",
    class: "Wizard",
    level: 2,
    alignment: "Neutral Good",
    background: "Sage",
    hitPoints: {
      current: 12,
      maximum: 14,
    },
    armorClass: 12,
    proficiencyBonus: 2,
    stats: {
      strength: 8,
      dexterity: 14,
      constitution: 13,
      intelligence: 16,
      wisdom: 12,
      charisma: 11,
    },
    skills: ["Arcana", "History", "Investigation", "Medicine"],
    equipment: ["Quarterstaff", "Dagger", "Spellbook", "Scholar's Pack", "Component Pouch"],
    spells: ["Magic Missile", "Shield", "Detect Magic", "Identify", "Sleep"],
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "3",
    campaignId: "2",
    name: "Finn Lightfinger",
    race: "Halfling",
    class: "Rogue",
    level: 2,
    alignment: "Chaotic Neutral",
    background: "Criminal",
    hitPoints: {
      current: 16,
      maximum: 16,
    },
    armorClass: 14,
    proficiencyBonus: 2,
    stats: {
      strength: 10,
      dexterity: 16,
      constitution: 12,
      intelligence: 13,
      wisdom: 11,
      charisma: 14,
    },
    skills: ["Stealth", "Sleight of Hand", "Deception", "Thieves' Tools", "Acrobatics"],
    equipment: ["Shortsword", "Shortbow", "Leather Armor", "Thieves' Tools", "Burglar's Pack"],
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-20"),
  },
]

export const mockLocations: Location[] = [
  {
    id: "1",
    campaignId: "1",
    name: "Phandalin",
    type: "city",
    description:
      "A small frontier town built on the ruins of a much older settlement. The town consists of forty or fifty simple log buildings, some built on old fieldstone foundations.",
    inhabitants: ["Toblen Stonehill", "Sister Garaele", "Harbin Wester", "Barthen"],
    connections: ["2", "3"],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    campaignId: "1",
    name: "Cragmaw Hideout",
    type: "dungeon",
    description:
      "A cave complex hidden in the woods, serving as a base for the Cragmaw goblins. The entrance is concealed behind a thicket of trees.",
    inhabitants: ["Klarg", "Yeemik", "Sildar Hallwinter"],
    connections: ["1"],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "3",
    campaignId: "1",
    name: "Tresendar Manor Ruins",
    type: "dungeon",
    description:
      "The ruins of an old manor house, now serving as a secret base for the Redbrands. Hidden beneath are ancient crypts and tunnels.",
    inhabitants: ["Glasstaff", "Redbrand Ruffians", "Nothic"],
    connections: ["1"],
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-16"),
  },
  {
    id: "4",
    campaignId: "1",
    name: "Stonehill Inn",
    type: "building",
    description:
      "A modest roadhouse of fieldstone and rough-hewn timbers. The inn smells of ale and roasted meat, and raucous laughter can be heard through the walls.",
    inhabitants: ["Toblen Stonehill", "Trilena Stonehill"],
    connections: ["1"],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "5",
    campaignId: "1",
    name: "Neverwinter Wood",
    type: "wilderness",
    description:
      "A large forest that stretches for miles, filled with ancient trees, hidden paths, and dangerous creatures. Many secrets lie within its depths.",
    inhabitants: ["Owlbears", "Wolves", "Bandits", "Wood Elves"],
    connections: ["1", "2"],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "6",
    campaignId: "2",
    name: "Village of Barovia",
    type: "city",
    description:
      "A grim village shrouded in perpetual mist, where the locals live in fear of their dark lord. The streets are eerily quiet, and shadows seem to move on their own.",
    inhabitants: ["Ismark Kolyanovich", "Ireena Kolyana", "Mad Mary", "Bildrath"],
    connections: [],
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
]

export const mockSessions: Session[] = [
  {
    id: "s1",
    campaignId: "1",
    name: "Goblin Ambush",
    description: "The party encounters goblins on the road to Phandalin",
    date: new Date("2024-01-20"),
    isCompleted: true,
    notes: "Party successfully defeated the goblins and rescued Sildar",
    sessionNumber: 1,
    isActive: false,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    summary: "The heroes began their journey and faced their first challenge on the road.",
  },
  {
    id: "s2",
    campaignId: "1",
    name: "Cragmaw Hideout",
    description: "Infiltrating the goblin stronghold",
    date: new Date("2024-01-27"),
    isCompleted: false,
    sessionNumber: 2,
    isActive: false,
    createdAt: new Date("2024-01-27"),
    updatedAt: new Date("2024-01-27"),
  },
  {
    id: "s3",
    campaignId: "2",
    name: "Death House",
    description: "The party explores the haunted mansion",
    date: new Date("2024-02-03"),
    isCompleted: false,
    sessionNumber: 1,
    isActive: false,
    createdAt: new Date("2024-02-03"),
    updatedAt: new Date("2024-02-03"),
  },
  {
    id: "s4",
    campaignId: "1",
    name: "Phandalin Troubles",
    description: "Investigating the Redbrands and their activities in town",
    date: new Date("2024-02-10"),
    isCompleted: false,
    sessionNumber: 3,
    isActive: true,
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },
]
