name: Quick Quality Check

on:
  push:
    branches-ignore: [ main, develop ]
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  quick-check:
    name: Quick Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Backend TypeScript check
        working-directory: ./backend
        run: npx tsc --noEmit

      - name: Frontend TypeScript check
        working-directory: ./frontend
        run: npx tsc --noEmit

      - name: Backend linting
        working-directory: ./backend
        run: npm run lint

      - name: Frontend linting
        working-directory: ./frontend
        run: npm run lint

      - name: Quick test run
        working-directory: ./frontend
        run: npm test -- --passWithNoTests --maxWorkers=2
